[package]
name = "mplay"
version = "0.1.0"
edition = "2021"

[dependencies]
also = "0.1.0"
pancurses = "0.17.0"
rodio = "0.19.0"

[dependencies.cursive]
version = "0.20.0"
default-features = false
features=["pancurses-backend"]
